/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BambooLayer: typeof import('./src/components/login/BambooLayer.vue')['default']
    BookGrid: typeof import('./src/components/home/BookGrid.vue')['default']
    CacheManagement: typeof import('./src/components/settings/CacheManagement.vue')['default']
    CaptchaChallengeModal: typeof import('./src/components/common/CaptchaChallengeModal.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DamageReportModal: typeof import('./src/components/damage/DamageReportModal.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    ErrorPage: typeof import('./src/components/common/ErrorPage.vue')['default']
    ErrorRetry: typeof import('./src/components/common/ErrorRetry.vue')['default']
    FeedbackToast: typeof import('./src/components/common/FeedbackToast.vue')['default']
    FormInput: typeof import('./src/components/common/FormInput.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    InkDiffusionCanvas: typeof import('./src/components/login/InkDiffusionCanvas.vue')['default']
    LibraryButton: typeof import('./src/components/common/LibraryButton.vue')['default']
    LoadingOverlay: typeof import('./src/components/common/LoadingOverlay.vue')['default']
    LoginAuthCard: typeof import('./src/components/login/LoginAuthCard.vue')['default']
    LoginVisualLayer: typeof import('./src/components/login/LoginVisualLayer.vue')['default']
    MistLayer: typeof import('./src/components/login/MistLayer.vue')['default']
    MountainLayer: typeof import('./src/components/login/MountainLayer.vue')['default']
    NotificationPanel: typeof import('./src/components/panels/NotificationPanel.vue')['default']
    OfflineIndicator: typeof import('./src/components/common/OfflineIndicator.vue')['default']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    PageScaffold: typeof import('./src/components/layout/PageScaffold.vue')['default']
    QuickActionPanel: typeof import('./src/components/panels/QuickActionPanel.vue')['default']
    QuickRenewModal: typeof import('./src/components/panels/QuickRenewModal.vue')['default']
    RelatedVolumes: typeof import('./src/components/home/RelatedVolumes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHistoryPanel: typeof import('./src/components/panels/SearchHistoryPanel.vue')['default']
    SidebarFilters: typeof import('./src/components/home/SidebarFilters.vue')['default']
    SiteFooter: typeof import('./src/components/home/SiteFooter.vue')['default']
    SuperButton: typeof import('./src/components/home/SuperButton.vue')['default']
    SyncStatus: typeof import('./src/components/common/SyncStatus.vue')['default']
    ToastContainer: typeof import('./src/components/common/ToastContainer.vue')['default']
    TopNav: typeof import('./src/components/navigation/TopNav.vue')['default']
  }
}
