#!/bin/bash
# 快速安装指南

echo "=========================================="
echo "  DDoS 防御系统 - 快速安装"
echo "=========================================="
echo ""
echo "项目统计:"
echo "- 总代码行数: 783 行"
echo "- 脚本文件: 5 个"
echo "- 配置文件: 5 个"
echo "- 文档文件: 4 个"
echo "- 总文件数: 17 个"
echo ""
echo "=========================================="
echo "  安装选项"
echo "=========================================="
echo ""
echo "选项 1: 一键自动安装（推荐）"
echo "  chmod +x deploy.sh"
echo "  sudo ./deploy.sh"
echo ""
echo "选项 2: 手动分步安装"
echo "  1. sudo ./scripts/system-optimize.sh"
echo "  2. sudo ./scripts/firewall-setup.sh"
echo "  3. 配置 Nginx (可选)"
echo "  4. 配置 Fail2ban (可选)"
echo "  5. 启动监控脚本"
echo ""
echo "选项 3: 仅测试（不安装）"
echo "  sudo ./scripts/status-check.sh"
echo ""
echo "=========================================="
echo "  文档位置"
echo "=========================================="
echo ""
echo "- 完整文档: docs/README.md"
echo "- 快速参考: docs/QUICK-REFERENCE.md"
echo "- 项目总结: PROJECT-SUMMARY.md"
echo "- 主页: README.md"
echo ""
echo "=========================================="
echo "  重要提示"
echo "=========================================="
echo ""
echo "⚠️  部署前请务必:"
echo "  1. 备份现有配置"
echo "  2. 在测试环境验证"
echo "  3. 确保 SSH 端口可访问"
echo "  4. 添加可信 IP 到白名单"
echo ""
echo "=========================================="
